### ISSUE TITLE
Browse Seassons

### ISSUE THREAD

**Issue by Morb0** [1s3k3b/hanime-api#2]
Hey,
Are you interested to add a method to fetch seasons endpoint?
Seasons endpoint allows to get videos by a range of date, have offset pagination and 500 records per page limit.

**Comment by 1s3k3b** [comment]
Apologies, didn't see the issue. Sure, that sounds useful, what exactly is the endpoint, if you know it?

**Comment by Morb0** [comment]
Here example: `https://hr.ha ni me.tv/api/v8/he nt ai_videos?source=browse-seasons&__order=released_at,DESC&released_at__gte=2020-01-01&released_at__lt=2021-01-01`

`source` static value need to be set `browse-seasons`

`__order` can use any field from response video model and `ASC`/`DESC` for ordering
Examples:
`views,ASC`
`name,DESC`

At least one of this fields required (can be used both): `released_at__gte`, `released_at__lt`
Accept date in format: `YYYY-MM-DD`

By default endpoint limited to `500` videos per page. `__offset` can be used to paginate.

**Comment by 1s3k3b** [comment]
I'll add it then, thank you.

**Comment by 1s3k3b** [comment]
Done in commit 25e4635, published version 1.3.0 on npm. Thanks again!
