### ISSUE TITLE
integrate api into a project; Result Problems.

### ISSUE THREAD

**Issue by gabrielwsy** [1s3k3b/hanime-api#3]
Hello, I'm having difficulty with the result, could you help me?
I want to put api in a bot.
I'm not able to write the result, it could help me.
for example:
sendFileUrl (from, 'video title, duration, etc.')

codigo-base: `sendFileFromUrl(to: ChatId, url: string, filename: string, caption: Content, quotedMsgId?: MessageId, requestConfig?: any, waitForId?: boolean, ptt?: boolean, withoutPreview?: boolean): any`

**Comment by 1s3k3b** [comment]
Sorry, I'd rather not provide assistance which requires more information here, please contact me on Discord: 1s3k3b#0001

**Comment by gabrielwsy** [comment]
> Sorry, I'd rather not provide assistance which requires more information here, please contact me on Discord: #1

ok, understand.
